#!/usr/bin/env bun
/*
 * Regenerate scripts/coverage-preload.ts by globbing every TypeScript file
 * under src/infra, src/composition, and src/presenter and emitting a fresh
 * preload that side-effect-imports each one.
 *
 * Why this exists:
 *
 *   `bun test --coverage` only emits rows for files the runner imports.
 *   Untested files in src/infra / src/composition / src/presenter are
 *   silently absent from the coverage table, which makes the per-file gate
 *   trivially pass (a file at 0% is invisible, not failing).
 *
 *   coverage-preload.ts side-effect-imports every such file so they appear
 *   in the table at 0% if untested, which makes the gate fail loudly.
 *
 *   But that file is a manual chore: every new adapter or wiring file means
 *   one more line, and forgetting it silently masks a coverage hole. This
 *   script regenerates the whole preload from the filesystem so the chore
 *   becomes deterministic.
 *
 * Usage:
 *
 *   bun run scripts/regenerate-coverage-preload.ts
 *     # writes scripts/coverage-preload.ts (or `--out <path>` for elsewhere)
 *
 *   bun run scripts/regenerate-coverage-preload.ts --check
 *     # exits non-zero if the on-disk file is out of sync with the glob;
 *     # use this in CI or pre-commit so a missing import blocks the merge.
 *
 * Wire it into pre-commit as an unnumbered pre-flight (the gates stay 1..8):
 *
 *   echo "[pre-flight] coverage-preload sync" >&2
 *   bun run scripts/regenerate-coverage-preload.ts --check
 *
 * Tune SCAN_DIRS below if your project's Clean Architecture layout differs.
 *
 * See skills/atelier/references/workflow.md (Coverage gates).
 */

import { readdirSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';

type Args = {
  readonly check: boolean;
  readonly out: string;
};

const SCAN_DIRS: ReadonlyArray<string> = ['src/infra', 'src/composition', 'src/presenter'];

// Files in scan dirs that should NOT be preloaded. Tests are obvious; ports
// are type-only and have no runtime to preload; index.ts files are usually
// barrel exports already pulled in by their siblings.
const EXCLUDE = (relPath: string): boolean => relPath.endsWith('.test.ts') || relPath.includes('/ports/') || relPath.endsWith('/index.ts');

const parseArgs = (argv: ReadonlyArray<string>): Args => {
  const check = argv.includes('--check');
  const outIdx = argv.indexOf('--out');
  const candidate = outIdx >= 0 ? argv[outIdx + 1] : undefined;
  const out = candidate ?? 'scripts/coverage-preload.ts';
  return { check, out };
};

const walk = (dir: string, repoRoot: string, acc: string[]): void => {
  let entries: ReadonlyArray<string>;
  try {
    entries = readdirSync(dir);
  } catch {
    return; // dir does not exist; harmless
  }
  for (const entry of entries) {
    const full = join(dir, entry);
    const st = statSync(full);
    if (st.isDirectory()) {
      walk(full, repoRoot, acc);
    } else if (st.isFile() && entry.endsWith('.ts')) {
      const rel = relative(repoRoot, full);
      if (!EXCLUDE(rel)) acc.push(rel);
    }
  }
};

const collectFiles = (repoRoot: string): ReadonlyArray<string> => {
  const acc: string[] = [];
  for (const scan of SCAN_DIRS) walk(join(repoRoot, scan), repoRoot, acc);
  return acc.sort();
};

const HEADER = `/*
 * Auto-generated by scripts/regenerate-coverage-preload.ts. Do not hand-edit;
 * run \`bun run scripts/regenerate-coverage-preload.ts\` to rewrite.
 *
 * \`bun test --coverage\` only emits rows for files the runner imports. Untested
 * src/infra, src/composition, and src/presenter files are silently absent
 * from the table — which makes the per-file gate trivially pass. This preload
 * side-effect-imports every such file so they appear at 0% (or better) and
 * the gate can fail loudly.
 *
 * Wired ONLY at coverage time, NOT in bunfig.toml. \`scripts/check-coverage.ts\`
 * spawns \`bun test --coverage --preload ./scripts/coverage-preload.ts\`.
 *
 * See skills/atelier/references/workflow.md.
 */`;

const buildContent = (files: ReadonlyArray<string>, repoRoot: string, outPath: string): string => {
  const grouped = new Map<string, string[]>();
  for (const f of files) {
    const top = SCAN_DIRS.find((d) => f.startsWith(`${d}/`)) ?? 'other';
    const list = grouped.get(top) ?? [];
    list.push(f);
    grouped.set(top, list);
  }

  // Imports are written relative to the output file's directory.
  const outDir = join(repoRoot, outPath, '..');

  const lines: string[] = [HEADER];
  for (const dir of SCAN_DIRS) {
    const list = grouped.get(dir);
    if (!list || list.length === 0) continue;
    lines.push('', `// --- ${dir}/ ---`);
    for (const f of list) {
      const fromOut = relative(outDir, join(repoRoot, f));
      const importPath = fromOut.startsWith('.') ? fromOut : `./${fromOut}`;
      lines.push(`import '${importPath}';`);
    }
  }
  lines.push(''); // trailing newline
  return lines.join('\n');
};

const main = async (): Promise<number> => {
  const args = parseArgs(process.argv.slice(2));
  const repoRoot = process.cwd();
  const files = collectFiles(repoRoot);
  const content = buildContent(files, repoRoot, args.out);

  if (args.check) {
    const existing = await Bun.file(args.out)
      .text()
      .catch(() => '');
    if (existing.trim() === content.trim()) {
      console.log(`coverage-preload: in sync (${files.length} files)`);
      return 0;
    }
    console.error('coverage-preload: OUT OF SYNC.');
    console.error(`  ${args.out} does not match the current set of source files.`);
    console.error('  Run: bun run scripts/regenerate-coverage-preload.ts');
    console.error(`  Then: git add ${args.out} && commit.`);
    return 1;
  }

  await Bun.write(args.out, content);
  console.log(`coverage-preload: wrote ${args.out} (${files.length} files)`);
  return 0;
};

process.exit(await main());
